### ISSUE TITLE
Is it possible to use potMachine with xhyve?

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [ebarriosjr/potMachine#8] opened 2020-02-19 08:34 UTC
Hello,

potMachine looks great it's the missing piece of FreeBSD development on macOS and Linux.
It'd great if it can be used with xhyve on macOS.

**Comment by grembo** [comment] 2020-02-19 11:10
> Hello,
> 
> potMachine looks great it's the missing piece of FreeBSD development on macOS and Linux.
> It'd great if it can be used with xhyve on macOS.

Is there a stable xhyve provider for vagrant? I've seen various ones while googling, but it was unclear if they actually work/are still maintained.

Same for FreeBSD, seems like there is no working bhyve provider for vagrant.

Ideally potMachine would also support FreeBSD the same way as it does Linux and Mac, so that developer workflows are identical on all three platforms.

**Comment by ebarriosjr** [comment] 2020-02-19 11:14
Hi @mateuszkwiatkowski 
I did a little digging and it seems possible to add a vagrant plugin to talk to xhyve. Will try to set it up.

**Comment by ebarriosjr** [comment] 2020-02-24 11:17
Hi @mateuszkwiatkowski, i manage to get the xhyve VM working. The problem is that you need to also tweak the vagrant-xhyve plugin to allow for freebsd machines. (long story short: the plugin has kexec hardcoded in the -f parameter for xhyve. So you need to change that also to fbsd). I will be adding this code to the repo this week.

**Comment by mateuszkwiatkowski** [comment] 2020-02-25 10:57
@ebarriosjr That sounds great! Thank you for looking into it!

**Comment by ebarriosjr** [comment] 2020-02-29 21:21
@mateuszkwiatkowski could you test this? I put in the readme the only thing you need to do is a
```
$ brew install xhyve
```
build the binary from master:
```
$ cd $GOPATH
$ go get github.com/ebarriosjr/potMachine
$ cd $GOPATH/src/github.com/ebarriosjr/potMachine
$ git checkout master
$ git pull
$ go build .
$ mv potMachine /usr/local/bin/pot
```
and run:
``` 
$ pot machine init xhyve
```
Please let me know if you find any bugs :)

**Comment by ebarriosjr** [comment] 2020-03-09 11:53
Closing issue.

**Comment by mateuszkwiatkowski** [comment] 2020-03-13 11:19
Hi @ebarriosjr 

Many thanks for working on this. I followed your instruction but there's something wrong with `machine init` command:
```
$ pot machine init xhyve
==> Initializing xhyve potMachine for the first time....
==> Creating ~/.pot/xhyve directory
==> Checking if tar file already exists on ~/.pot/xhyve/potMachine.tar.gz
==> Downloading tar file to ~/.pot/xhyve/potMachine.tar.gz
==> 0s remaining...==> Extracting tar file ~/.pot/xhyve/potMachine.tar.gz to ~/.pot/xhyve/
==> Download is completed
==> Cleaning up ~/.pot/xhyve/
==> Enabeling nfs mountpoint
Password:
==> Waiting for machine to start...
==> Machine started with ip:  192.168.64.3
==> Local IP:  192.168.64.1

==> nfsd restarted
mount: 192.168.64.1: unknown special file or file system
bash: line 1: :/Users/kwiat/.pot: No such file or directory
```

**Comment by ebarriosjr** [comment] 2020-03-13 13:45
Could you please share your /etc/exports file? Specially the lines between 
```
# POTMACHINE-Xhyve-Begin

# POTMACHINE-Xhyve-END

```
And please try the new publish binary v0.1.1

**Comment by mateuszkwiatkowski** [comment] 2020-03-15 18:51
```
$ cat /etc/exports
# POTMACHINE-Xhyve-Begin
/Users/kwiat/.pot/ -alldirs -mapall=501
# POTMACHINE-Xhyve-END
```

**Comment by ebarriosjr** [comment] 2020-03-20 12:30
That looks good. Can you please retry with the new release? v0.1.1

**Closed as completed** 2020-04-29 23:43 UTC
Labels: enhancement
